### ISSUE TITLE
Bad SSR usage + optimizations

### ISSUE THREAD

**Issue by cvxluo** [GTBitsOfGood/access-h2o#179] opened 2022-10-11 18:33 UTC
Several instances of bad SSR usage or too many calls being made before a page load has caused some extremely long loading times:
- ex. ApplicantViewPage should have just use getServerSideProps in src/pages/...
- authentication system seems to cause some longer loading times (ex. try to load into https://access-h2o.vercel.app/login, often takes a while or times out) 
- could also be package size related - maybe solved by moving some dependencies to dev
- some pages don't necessarily need SSR at all - ex. ApplicantViewTable can just load in retrieved clients on the client side dynamically if it improves loading time

**Comment by XenonMolecule** [comment] 2022-10-30 06:16
I am not certain about this but after performing some testing I think this is not as big of a problem with the SSR usage, but rather the time it takes vercel to launch the server.  I recognize this issue from deploying Heroku dynos.  The first load is really slow but the others are really quick.

See this reddit discussion about how vercel puts lambdas to sleep [here](https://www.reddit.com/r/nextjs/comments/qvt7vc/slow_first_load/)

Test to replicate:
- Load up the website one time (should be slow if nobody else used it recently) [here](https://access-h2o.vercel.app/login)
- Do it again.  This time the load will be fast!
- You might think the page is cached or that it uses cookies so try in an incognito tab (still fast!)
- Okay but maybe it is storing locally somehow?  Try another computer (still fast!)

This might be an issue with deploying using vercel and not just a problem with SSR usage.  I have also looked into the SSR usage and I do think it may be poorly designed, however.  Certainly, not every page needs to wait to load until the server can be pinged especially something like a login page that looks the same for each user.

My final conclusion of the investigation so far: Yes we are using SSR wrong but this change might be putting a bandaid on the slow initial load times of the vercel deployment.  I am going to need to dedicate some more engineering time if we are certain we need to fix SSR because it will involve refactoring several parts of the app to use this pattern instead [nextjs docs](https://nextjs.org/docs/basic-features/data-fetching/client-side).  On my initial scan, I noticed 4 parts of the app that use unoptimized SSR.  This will be the outcome of the refactor:  Pages will show up with a loading sign until vercel wakes up the lambda function instead of pages showing as blank to the user.  The user experience will be better, but I expect the load times to only improve marginally.

These are the necessary steps to fix this problem (might take another sprint or two to fully complete):

**Applicant View Page**
- [ ] Render an empty table and loading sign
- [ ] Wait for getAll to return all applicant data
- [ ] BONUS: Split the getAll requests so the table can be loaded into segments and reduce the loading time
- [ ] Ensure no regression by testing with mongo database and loading all applicants

**Profile Page**
- [ ] Loading symbol
- [ ] Wait until user data fetch
- [ ] Wait until company data fetch
- [ ] Render with data
- [ ] Ensure no regression by creating and testing with a user

**Login Page**
- [ ] Immediately load login (if get request later shows they are already logged in then we can redirect)
- [ ] Get current user
- [ ] If null leave them to login
- [ ] If not null redirect to appropriate next page
- [ ] Ensure no regression by logging in with a user (involves making a login)

**Applicant View Page (Utility View)**
- [ ] Mostly the changes to the original applicant view page should fix this one too
- [ ] I'm not sure the difference between the Utility View and Original Applicant View page, but both should be tested

**Comment by SamratSahoo** [comment] 2023-05-29 17:24
closed by PR #208

**Closed by SamratSahoo** 2023-05-29 17:24 UTC
Labels: bug, priority
